# https://taskfile.dev

version: '3'

vars:
  GREETING: Welcome to Gouniverse Dashboard!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  dev:init:
    cmds:
      - cp ./development/.env_example ./development/.env

  dev:
    cmds:
      - cd ./development; air